os: osx
osx_image: xcode9.1
language: node_js
node_js:
  - "8"
before_install:
  - brew update
branches:
  only:
    - /^v\d+(\.\d+)+$/
jobs:
  include:
    # - stage: Compile and Release app
    #   script: ./scripts/deploy.sh
    #   deploy:
    #     provider: releases
    #     api_key: $GITHUB_OAUTH_TOKEN
    #     file:
    #       - "dist/Sombrio-darwin-x64.zip"
    #       - "dist/Sombrio-linux-x64.zip"
    #       - "dist/Sombrio-win32-x64.zip"
    #     skip_cleanup: true
    #     on:
    #       tags: true
    - stage: Build Sombrio Website
      script:
        - ./scripts/deployWebsite.sh
        - git fetch --depth 1 origin gh-pages:gh-pages
        - git checkout gh-pages
        - rm -rf *.css *.map *.js *.html
        - unzip -o website.zip
        - git commit -am "Deploying website ${TRAVIS_TAG}"
        - git push --force gh-pages
