os: osx
language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: Compile app
      script: rvm list
    - script: rvm use ruby-2.3.4
    - script: brew install yarn
    - script: ./scripts/install.sh
    - script: ./scripts/distribute.sh
