os: osx
osx_image: xcode9.1
language: node_js
node_js:
  - "8"
before_install:
  - brew update
branches:
  only:
    - /^v\d+(\.\d+)+$/
jobs:
  include:
    - stage: Compile app
      script: ./scripts/deploy.sh
    - stage: Release app tag
      script: echo "Deploying to GitHub releases..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "FILE TO UPLOAD"
        skip_cleanup: true
        on:
          tags: true
