os: osx
osx_image: xcode9.1
language: node_js
node_js:
  - "8"
before_install:
  - brew update
branches:
  only:
    - /^v\d+(\.\d+)+$/
jobs:
  include:
    - stage: Compile app
      script: ./scripts/deploy.sh
