os: osx
osx_image: xcode9.1
language: node_js
node_js:
  - "8"
before_install:
  - brew update
branches:
  only:
    - /^v\d+(\.\d+)+$/
jobs:
  include:
    - stage: Compile and Release app
      script: ./scripts/deploy.sh
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "dist/Sombrio-darwin-x64.zip"
          - "dist/Sombrio-linux-x64.zip"
          - "dist/Sombrio-win32-x64.zip"
        skip_cleanup: true
        on:
          tags: true
    - stage: Build Sombrio Website
      script:
        - env
        - ./scripts/deployWebsite.sh ${TRAVIS_BRANCH}
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - git fetch --depth 1 origin gh-pages:gh-pages
        - git checkout gh-pages
        - rm -rf *.css *.map *.js *.html *.yml *.json *.php website/
        - unzip -o website.zip
        - rm *.zip
        - git add .
        - git commit -am "Deploying website ${TRAVIS_BRANCH}"
        - git remote add origin-pages https://$GITHUB_OAUTH_TOKEN@github.com/Hackbit/nko2017-sombrio.git > /dev/null 2>&1
        - git push --force --set-upstream origin-pages gh-pages
