os: osx
osx_image: xcode9.1
language: node_js
node_js:
  - "8"
before_install:
  - brew update
branches:
  only:
    - /^v\d+(\.\d+)+$/
jobs:
  include:
    - stage: Compile and Release app
      script: ./scripts/deploy.sh
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "dist/Sombrio-darwin-x64.zip"
          - "dist/Sombrio-linux-x64.zip"
          - "dist/Sombrio-win32-x64.zip"
        skip_cleanup: true
        on:
          tags: true
